[window]
opacity = 0.7

[font]
size = 15
normal = { family = "Hack Nerd Font", style = "Reguler" }
bold = { family = "Hack Nerd Font", style = "Bold" }
italic = { family = "Hack Nerd Font", style = "Italic" }
